name: Package Build and Test

on:
  push:
    branches: [ 'stable' ]
  pull_request:
    branches: [ 'stable', 'dev' ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        [ -f requirements.txt ] && python -m pip install -r requirements.txt

    - name: Build package
      run: |
        python -m pip install --upgrade build
        python -m build

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        [ -f requirements.txt ] && python -m pip install -r requirements.txt

    - name: Install package and testing dependencies
      run: |
        python -m pip install -e .
        python -m pip install pytest pytest-cov

    - name: Test with PyTest
      run: python -m pytest --cov=src/scoretree/core --cov-report=lcov --color=yes --capture=no --verbosity=3 src/scoretree/tests

    - name: Upload coverage file artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.lcov

  upload-coverage:

    runs-on: ubuntu-latest
    needs: test

    steps:

      - name: Download coverage file artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/coverage.lcov
          format: lcov
          flag-name: unit
          fail-on-error: false
