name: Python Test Execution

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable", "dev" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install and activate virtual environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install virtualenv
        python -m virtualenv .venv
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install pytest
        if [ -f requirements.txt ]; then
          python -m pip install -r requirements.txt
        fi

    - name: Install package from local source
      run: python -m pip install -e .

  run-tests:

    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Test with PyTest
      run: |
        if [ -d tests ]; then
          python -m pytest src/scoretree/tests
        fi
